flowchart TB
  n0["5th Edition"]
  n1["6th Edition"]
  n2["PWB 1.0"]
  n3["LSX"]
  n4["1 BSD"]
  n5["Mini Unix"]
  n6["Wollongong"]
  n7["Interdata"]
  n8["Unix/TS 3.0"]
  n9["PWB 2.0"]
  n10["7th Edition"]
  n11["8th Edition"]
  n12["32V"]
  n13["V7M"]
  n14["Ultrix-11"]
  n15["Xenix"]
  n16["UniPlus+"]
  n17["9th Edition"]
  n18["2 BSD"]
  n19["2.8 BSD"]
  n20["2.9 BSD"]
  n21["3 BSD"]
  n22["4 BSD"]
  n23["4.1 BSD"]
  n24["4.2 BSD"]
  n25["4.3 BSD"]
  n26["Ultrix-32"]
  n27["PWB 1.2"]
  n28["USG 1.0"]
  n29["CB Unix 1"]
  n30["USG 2.0"]
  n31["CB Unix 2"]
  n32["CB Unix 3"]
  n33["Unix/TS++"]
  n34["PDP-11 Sys V"]
  n35["USG 3.0"]
  n36["Unix/TS 1.0"]
  n37["TS 4.0"]
  n38["System V.0"]
  n39["System V.2"]
  n40["System V.3"]
  n0 --> n1
  n0 --> n2
  n1 --> n3
  n1 --> n4
  n1 --> n5
  n1 --> n6
  n1 --> n7
  n7 --> n8
  n7 --> n9
  n7 --> n10
  n10 --> n11
  n10 --> n12
  n10 --> n13
  n10 --> n14
  n10 --> n15
  n10 --> n16
  n13 --> n14
  n11 --> n17
  n4 --> n18
  n18 --> n19
  n19 --> n14
  n19 --> n20
  n12 --> n21
  n21 --> n22
  n22 --> n23
  n23 --> n24
  n23 --> n19
  n23 --> n11
  n24 --> n25
  n24 --> n26
  n2 --> n27
  n2 --> n28
  n27 --> n9
  n28 --> n29
  n28 --> n30
  n29 --> n31
  n31 --> n32
  n32 --> n33
  n32 --> n34
  n30 --> n35
  n35 --> n8
  n9 --> n8
  n36 --> n8
  n8 --> n37
  n33 --> n37
  n32 --> n37
  n37 --> n38
  n38 --> n39
  n39 --> n40